# Datasource
spring.datasource.url=jdbc:postgresql://database-1.c4bq6m0smyma.us-east-1.rds.amazonaws.com:5432/database-1?sslmode=require&sslfactory=org.postgresql.ssl.DefaultSSLFactory
spring.datasource.username=kca
spring.datasource.password=doit2027
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
